# .github/workflows/semgrep_summary.yml

name: 'Security Scan and Summarize'

on:
  pull_request:
    branches: [ main, master ]

# Permissions needed to read code and write PR comments
permissions:
  contents: read
  pull-requests: write

jobs:
  semgrep_scan:
    name: Semgrep Scan & LLM Summary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install semgrep google-generativeai requests

      # This step is updated to use your root rules.yaml and a standard ruleset
      - name: Run Semgrep
        run: |
          semgrep scan \
            --config "p/default" \
            --config "rules.yaml" \
            --json -o semgrep_results.json

      - name: Summarize and Comment
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          REPO_NAME: ${{ github.repository }}
        run: python .github/scripts/summarize.py
