name: Semgrep Scan

on:
  pull_request:   # Run on every PR
  push:           # (optional) Also run on push to branches
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep scan
        run: semgrep --config rules.yaml --error
        # --error makes the workflow FAIL if any violations are found
