name: 'Semgrep Rule Check'

on:
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  semgrep_scan:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: python -m pip install semgrep

      - name: Run Semgrep and Fail on Findings
        run: |
          semgrep ci \
            --config "rules.yaml" \
            --no-suppress-errors \
            --json > semgrep.json  # Generate JSON for sending

      - name: Send Results to Central Webhook
        if: always()  # Runs even if scan fails
        env:
          WEBHOOK_URL: https://semgrep-receiver.onrender.com/receiver  # Your central Render URL
          API_TOKEN: ${{ secrets.API_TOKEN }}  # Shared token
        run: |
          curl -v -X POST "$WEBHOOK_URL" \
            -H "Authorization: Bearer $API_TOKEN" \
            -H "Content-Type: application/json" \
            -d @semgrep.json
