jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep
        run: |
          pip install semgrep
          semgrep --config=auto --json > semgrep-results.json

      - name: Analyze with Gemini
        run: |
          pip install google-generativeai
          python scripts/gemini_review.py semgrep-results.json
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
