name: 'Semgrep Rule Check'

on:
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pull-requests: write  # Add permission to write PR comments

jobs:
  semgrep_scan:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: python -m pip install semgrep

      - name: Run Semgrep and Generate JSON
        run: |
          semgrep ci \
            --config "rules.yaml" \
            --no-suppress-errors \
            --json > semgrep.json || true  # Don't fail the step, let webhook handle it
        continue-on-error: true

      - name: Send Results to Central Webhook
        if: always()  # Always run, even if semgrep found issues
        env:
          WEBHOOK_URL: https://semgrep-receiver.onrender.com/receiver
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          curl -v -X POST "$WEBHOOK_URL" \
            -H "Authorization: Bearer $API_TOKEN" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Repository-Owner: ${{ github.repository_owner }}" \
            -H "X-GitHub-Repository-Name: ${{ github.event.repository.name }}" \
            -H "X-GitHub-PR-Number: ${{ github.event.pull_request.number }}" \
            -d @semgrep.json

      - name: Check Semgrep Results
        run: |
          # Check if there were any ERROR severity findings
          if jq -e '.results[] | select(.severity == "ERROR")' semgrep.json > /dev/null; then
            echo "❌ Critical security issues found. Check the PR comment for details."
            exit 1
          else
            echo "✅ No critical issues found."
          fi
